name       : beekeeper-studio
version    : 2.0.0
release    : 2
source     :
    - https://github.com/beekeeper-studio/beekeeper-studio/archive/refs/tags/v2.0.0.tar.gz : d2051a412a204ac2be7d4e11c9d1711b1df9df21b2e5f6a5e4f213e580393a51
license    : MIT
component  : programming.tools
summary    : Modern and easy to use SQL client for MySQL, Postgres, SQLite, SQL Server, and more
description: |
    Modern and easy to use SQL client for MySQL, Postgres, SQLite, SQL Server, and more.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(xshmfence)
    - yarn
setup      : |
    yarn install --frozen-lockfile
build      : |
    yarn bks:build
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/usr/share/beekeeper-studio

    # Install Desktop file
    install -Dm00644 $pkgfiles/beekeeper-studio.desktop $installdir/usr/share/applications/beekeeper-studio.desktop

    # Install Icons
    for icon_size in 16 24 48 64 96 128 256 512 1024
    do
        install -Dm00644 apps/studio/public/icons/png/${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/beekeeper-studio.png
    done
    install -Dm00644 apps/studio/public/icons/png/512x512.png $installdir/usr/share/pixmaps/beekeeper-studio.png

    # Install electron app bundle
    cp -R apps/studio/dist_electron/linux-unpacked/* $installdir/usr/share/beekeeper-studio
    mv $installdir/usr/share/beekeeper-studio/resources/public/* $installdir/usr/share/beekeeper-studio/resources/
    rmdir $installdir/usr/share/beekeeper-studio/resources/public

    ln -s /usr/share/beekeeper-studio/beekeeper-studio $installdir/usr/bin/beekeeper-studio
